# Specify the target

all: clean memory

memory: 
	gcc malloc.c -o tester

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f *.o *~ *.class *.so tester
